[features]
seeds = false
skip-lint = false
[programs.localnet]
wba_vault = "BaRtR9LkkzMWysBndwLf1wwWyHTHCYEGiPPa2ooXmodW"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/beliv/wba/q2starter/solana-Q2-starter/ts/wba-wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
